// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function rgbString(r, g, b) {
  return "rgb(" + (String(r) + ("," + (String(g) + ("," + (String(b) + ")")))));
}

function drawPixel(t, x, y, r, g, b) {
  t.fillStyle = rgbString(r, g, b);
  t.fillRect(x, y, 1, 1);
  return /* () */0;
}

var Context = /* module */[
  /* rgbString */rgbString,
  /* drawPixel */drawPixel
];

var Canvas = /* module */[];

var Document = /* module */[];

exports.Context = Context;
exports.Canvas = Canvas;
exports.Document = Document;
/* No side effect */
