// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function make(t, p, normal, material) {
  return /* record */[
          /* t */t,
          /* p */p,
          /* normal */normal,
          /* material */material
        ];
}

exports.make = make;
/* No side effect */
