// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(t, p, normal, material) {
  return {
          t: t,
          p: p,
          normal: normal,
          material: material
        };
}

exports.make = make;
/* No side effect */
