// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ray$RayTracer = require("./Ray.bs.js");
var Vec3$RayTracer = require("./Vec3.bs.js");
var SphereUtils$RayTracer = require("./SphereUtils.bs.js");

function scatter(_rayIn, hitNormal, hitP, albedo) {
  var target = Vec3$RayTracer.add(Vec3$RayTracer.add(hitP, hitNormal), SphereUtils$RayTracer.randomVectorInUnitSphere(undefined));
  var scattered = Ray$RayTracer.make(hitP, Vec3$RayTracer.sub(target, hitP));
  return [
          albedo,
          scattered
        ];
}

exports.scatter = scatter;
/* No side effect */
