// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ray$RayTracer = require("./Ray.bs.js");
var Vec3$RayTracer = require("./Vec3.bs.js");
var SphereUtils$RayTracer = require("./SphereUtils.bs.js");

function reflect(v, n) {
  var a = Vec3$RayTracer.mul(n, Vec3$RayTracer.dot(v, n) * 2.0);
  return Vec3$RayTracer.sub(v, a);
}

function scatter(rayIn, hitNormal, hitP, albedo, fuzziness) {
  var fuzz = fuzziness > 1.0 ? 1.0 : fuzziness;
  var reflected = reflect(Vec3$RayTracer.unitVector(rayIn.direction), hitNormal);
  var scattered = Ray$RayTracer.make(hitP, Vec3$RayTracer.add(reflected, Vec3$RayTracer.mul(SphereUtils$RayTracer.randomVectorInUnitSphere(undefined), fuzz)));
  if (Vec3$RayTracer.dot(scattered.direction, hitNormal) > 0.0) {
    return [
            albedo,
            scattered
          ];
  }
  
}

exports.reflect = reflect;
exports.scatter = scatter;
/* No side effect */
