// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Vec3$RayTracer = require("./Vec3.bs.js");

function make(origin, direction) {
  return /* record */[
          /* origin */origin,
          /* direction */direction
        ];
}

function pointAtParameter(ray, t) {
  return Vec3$RayTracer.add(ray[/* origin */0], Vec3$RayTracer.mul(ray[/* direction */1], t));
}

exports.make = make;
exports.pointAtParameter = pointAtParameter;
/* No side effect */
