// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vec3$RayTracer = require("./Vec3.bs.js");

function make(origin, direction) {
  return {
          origin: origin,
          direction: direction
        };
}

function pointAtParameter(ray, t) {
  return Vec3$RayTracer.add(ray.origin, Vec3$RayTracer.mul(ray.direction, t));
}

exports.make = make;
exports.pointAtParameter = pointAtParameter;
/* No side effect */
