// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function make(x, y, z) {
  return /* record */[
          /* x */x,
          /* y */y,
          /* z */z
        ];
}

function add(vec1, vec2) {
  return /* record */[
          /* x */vec1[/* x */0] + vec2[/* x */0],
          /* y */vec1[/* y */1] + vec2[/* y */1],
          /* z */vec1[/* z */2] + vec2[/* z */2]
        ];
}

function sub(vec1, vec2) {
  return /* record */[
          /* x */vec1[/* x */0] - vec2[/* x */0],
          /* y */vec1[/* y */1] - vec2[/* y */1],
          /* z */vec1[/* z */2] - vec2[/* z */2]
        ];
}

function div(vec, f) {
  return /* record */[
          /* x */vec[/* x */0] / f,
          /* y */vec[/* y */1] / f,
          /* z */vec[/* z */2] / f
        ];
}

function mul(vec, f) {
  return /* record */[
          /* x */vec[/* x */0] * f,
          /* y */vec[/* y */1] * f,
          /* z */vec[/* z */2] * f
        ];
}

function mulVector(vec1, vec2) {
  return /* record */[
          /* x */vec1[/* x */0] * vec2[/* x */0],
          /* y */vec1[/* y */1] * vec2[/* y */1],
          /* z */vec1[/* z */2] * vec2[/* z */2]
        ];
}

function dot(vec1, vec2) {
  return vec1[/* x */0] * vec2[/* x */0] + vec1[/* y */1] * vec2[/* y */1] + vec1[/* z */2] * vec2[/* z */2];
}

function cross(vec1, vec2) {
  return /* record */[
          /* x */vec1[/* y */1] * vec2[/* z */2] - vec2[/* y */1] * vec1[/* z */2],
          /* y */vec1[/* z */2] * vec2[/* x */0] - vec2[/* z */2] * vec1[/* x */0],
          /* z */vec1[/* x */0] * vec2[/* y */1] - vec2[/* x */0] * vec1[/* y */1]
        ];
}

function length(vec) {
  return Math.sqrt(vec[/* x */0] * vec[/* x */0] + vec[/* y */1] * vec[/* y */1] + vec[/* z */2] * vec[/* z */2]);
}

function squaredLength(vec) {
  return vec[/* x */0] * vec[/* x */0] + vec[/* y */1] * vec[/* y */1] + vec[/* z */2] * vec[/* z */2];
}

function unitVector(vec) {
  return div(vec, length(vec));
}

exports.make = make;
exports.add = add;
exports.sub = sub;
exports.div = div;
exports.mul = mul;
exports.mulVector = mulVector;
exports.dot = dot;
exports.cross = cross;
exports.length = length;
exports.squaredLength = squaredLength;
exports.unitVector = unitVector;
/* No side effect */
