// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function printCombined(one, two) {
  console.log(one + two);
  return /* () */0;
}

printCombined("sous", "vide");

var one = "foo";

printCombined(one, "bar");

function multiply(x, $staropt$star, param) {
  var y = $staropt$star !== undefined ? $staropt$star : 2;
  return Caml_int32.imul(x, y);
}

var y = 2;

console.log(Caml_int32.imul(3, y));

function multiplyTwo(x, $staropt$star, _unused) {
  var y = $staropt$star !== undefined ? $staropt$star : 2;
  return Caml_int32.imul(x, y);
}

var y$1 = 2;

console.log(Caml_int32.imul(3, y$1));

function toFixed(prim, prim$1) {
  return prim.toFixed(prim$1);
}

console.log((3.1415926).toFixed(2));

var times = Caml_int32.imul;

function timesTwo(param) {
  return (param << 1);
}

function timesThree(param) {
  return Caml_int32.imul(param, 3);
}

console.log(10);

console.log(15);

exports.printCombined = printCombined;
exports.one = one;
exports.multiply = multiply;
exports.multiplyTwo = multiplyTwo;
exports.toFixed = toFixed;
exports.times = times;
exports.timesTwo = timesTwo;
exports.timesThree = timesThree;
/*  Not a pure module */
