// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var _s = 3;

"a string".length;

console.log("Result is " + (String(5.43) + ""));

console.log("Prix avant re\xcc\x81duction: " + (Pervasives.string_of_float(5.43) + " \xe2\x82\xac"));

console.log("Prix avant réduction: " + (Pervasives.string_of_float(5.43) + " €"));

var result = 5.43;

exports._s = _s;
exports.result = result;
/*  Not a pure module */
