// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function reverse(theList) {
  var _l = theList;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var l = _l;
    if (l) {
      _acc = /* :: */[
        l[0],
        acc
      ];
      _l = l[1];
      continue ;
    } else {
      return acc;
    }
  };
}

exports.reverse = reverse;
/* No side effect */
