// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function reverse(theList) {
  var _l = theList;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var l = _l;
    if (!l) {
      return acc;
    }
    _acc = {
      hd: l.hd,
      tl: acc
    };
    _l = l.tl;
    continue ;
  };
}

exports.reverse = reverse;
/* No side effect */
