// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Stack$ReasonExamples = require("./data-structures/Stack.bs.js");
var StringFns$ReasonExamples = require("./StringFns.bs.js");

function is_balanced(str) {
  var _stack = Stack$ReasonExamples.make(undefined);
  var _s = StringFns$ReasonExamples.string_to_list(str);
  while(true) {
    var s = _s;
    var stack = _stack;
    if (!s) {
      return Stack$ReasonExamples.is_empty(stack);
    }
    switch (s.hd) {
      case "(" :
          _s = s.tl;
          _stack = Stack$ReasonExamples.push("(", stack);
          continue ;
      case ")" :
          var match = Stack$ReasonExamples.pop(stack);
          if (match[0] !== "(") {
            return false;
          }
          _s = s.tl;
          _stack = match[1];
          continue ;
      case "{" :
          _s = s.tl;
          _stack = Stack$ReasonExamples.push("{", stack);
          continue ;
      case "}" :
          var match$1 = Stack$ReasonExamples.pop(stack);
          if (match$1[0] !== "{") {
            return false;
          }
          _s = s.tl;
          _stack = match$1[1];
          continue ;
      default:
        _s = s.tl;
        continue ;
    }
  };
}

exports.is_balanced = is_balanced;
/* No side effect */
