// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function string_to_list(str) {
  return $$Array.to_list(str.split(""));
}

exports.string_to_list = string_to_list;
/* No side effect */
