// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Empty_list = /* @__PURE__ */Caml_exceptions.create("LinkedList-ReasonExamples.Empty_list");

function make(param) {
  return /* Empty */0;
}

function cons(x, l) {
  if (l) {
    return /* Node */{
            _0: x,
            _1: l
          };
  } else {
    return /* Node */{
            _0: x,
            _1: /* Empty */0
          };
  }
}

function head(l) {
  if (l) {
    return l._0;
  }
  throw {
        RE_EXN_ID: Empty_list,
        Error: new Error()
      };
}

function tail(l) {
  if (l) {
    return l._1;
  }
  throw {
        RE_EXN_ID: Empty_list,
        Error: new Error()
      };
}

exports.Empty_list = Empty_list;
exports.make = make;
exports.cons = cons;
exports.head = head;
exports.tail = tail;
/* No side effect */
