// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Empty_list = Caml_exceptions.create("LinkedList-ReasonExamples.Empty_list");

function make(param) {
  return /* Empty */0;
}

function cons(x, l) {
  if (l) {
    return /* Node */[
            x,
            l
          ];
  } else {
    return /* Node */[
            x,
            /* Empty */0
          ];
  }
}

function head(l) {
  if (l) {
    return l[0];
  } else {
    throw Empty_list;
  }
}

function tail(l) {
  if (l) {
    return l[1];
  } else {
    throw Empty_list;
  }
}

exports.Empty_list = Empty_list;
exports.make = make;
exports.cons = cons;
exports.head = head;
exports.tail = tail;
/* No side effect */
