// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(param) {
  return /* [] */0;
}

function push(x, stack) {
  return {
          hd: x,
          tl: stack
        };
}

function pop(stack) {
  if (stack) {
    return [
            stack.hd,
            stack.tl
          ];
  }
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

function peek(stack) {
  if (stack) {
    return stack.hd;
  } else {
    return 0;
  }
}

function is_empty(stack) {
  if (stack) {
    return false;
  } else {
    return true;
  }
}

exports.make = make;
exports.push = push;
exports.pop = pop;
exports.peek = peek;
exports.is_empty = is_empty;
/* No side effect */
