// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var ListLabels = require("bs-platform/lib/js/listLabels.js");

function make() {
  return /* Empty */0;
}

function to_array(li) {
  var acc = /* array */[];
  var _l = li;
  while(true) {
    var l = _l;
    if (l) {
      acc.push(l[0]);
      _l = l[1];
      continue ;
    } else {
      return acc;
    }
  };
}

function to_reason_list(li) {
  var do_to_reason_list = function (_l, _acc) {
    while(true) {
      var acc = _acc;
      var l = _l;
      if (l) {
        _acc = /* :: */[
          l[0],
          acc
        ];
        _l = l[1];
        continue ;
      } else {
        return acc;
      }
    };
  };
  return ListLabels.rev(do_to_reason_list(li, /* [] */0));
}

function cons(x, l) {
  if (l) {
    return /* Node */[
            x,
            l
          ];
  } else {
    return /* Node */[
            x,
            /* Empty */0
          ];
  }
}

exports.make = make;
exports.to_array = to_array;
exports.to_reason_list = to_reason_list;
exports.cons = cons;
/* No side effect */
