// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';


function make() {
  return /* [] */0;
}

function push(x, stack) {
  return /* :: */[
          x,
          stack
        ];
}

function pop(stack) {
  if (stack) {
    return /* tuple */[
            stack[0],
            stack[1]
          ];
  } else {
    return /* tuple */[
            0,
            /* [] */0
          ];
  }
}

function peek(stack) {
  if (stack) {
    return stack[0];
  } else {
    return 0;
  }
}

exports.make = make;
exports.push = push;
exports.pop = pop;
exports.peek = peek;
/* No side effect */
