// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var floats = 1.212 * 3.4384;

console.log("Amount: $" + (7.24242344).toFixed(2));

var _result = Math.sqrt(Math.abs(-3.75));

var area = Math.PI * 5.0 * 5.0;

console.log(Math.random());

var ints = 12;

var r = 5.0;

exports.ints = ints;
exports.floats = floats;
exports._result = _result;
exports.r = r;
exports.area = area;
/*  Not a pure module */
