// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var _s = 3;

console.log("Result is " + 5.43);

console.log("Prix avant re\xcc\x81duction: " + ((5.43).toString() + " \xe2\x82\xac"));

console.log("Prix avant réduction: " + ((5.43).toString() + " €"));

var result = 5.43;

exports._s = _s;
exports.result = result;
/*  Not a pure module */
