// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function price(d) {
  switch (d) {
    case /* Coffee */0 :
        return 2.45;
    case /* Tea */1 :
        return 3.78;
    case /* EggCream */2 :
        return 1.67;
    
  }
}

console.log(2.45);

function stringOfDrink(drinkType) {
  switch (drinkType) {
    case /* Coffee */0 :
        return "Coffee";
    case /* Tea */1 :
        return "Tea";
    case /* EggCream */2 :
        return "EggCream";
    
  }
}

console.log("Tea");

function stringOfShirtSize(size) {
  if (typeof size !== "number") {
    return $$String.make(size._0, /* 'X' */88) + "L";
  }
  switch (size) {
    case /* Small */0 :
        return "S";
    case /* Medium */1 :
        return "M";
    case /* Large */2 :
        return "L";
    
  }
}

var veryLarge = /* XLarge */{
  _0: 2
};

console.log(stringOfShirtSize(veryLarge));

exports.price = price;
exports.stringOfDrink = stringOfDrink;
exports.stringOfShirtSize = stringOfShirtSize;
exports.veryLarge = veryLarge;
/*  Not a pure module */
