// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function price(d) {
  switch (d) {
    case 0 : 
        return 2.45;
    case 1 : 
        return 3.78;
    case 2 : 
        return 1.67;
    
  }
}

console.log(2.45);

function stringOfDrink(drinkType) {
  switch (drinkType) {
    case 0 : 
        return "Coffee";
    case 1 : 
        return "Tea";
    case 2 : 
        return "EggCream";
    
  }
}

console.log("Tea");

function stringOfShirtSize(size) {
  if (typeof size === "number") {
    switch (size) {
      case 0 : 
          return "S";
      case 1 : 
          return "M";
      case 2 : 
          return "L";
      
    }
  } else {
    return $$String.make(size[0], /* "X" */88) + "L";
  }
}

var veryLarge = /* XLarge */[2];

console.log(stringOfShirtSize(veryLarge));

exports.price = price;
exports.stringOfDrink = stringOfDrink;
exports.stringOfShirtSize = stringOfShirtSize;
exports.veryLarge = veryLarge;
/*  Not a pure module */
