// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';


function reverse(arr) {
  var _arr = arr;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var arr$1 = _arr;
    if (arr$1) {
      _acc = /* :: */[
        arr$1[0],
        acc
      ];
      _arr = arr$1[1];
      continue ;
    } else {
      return acc;
    }
  };
}

exports.reverse = reverse;
/* No side effect */
