// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

var reasonArray = /* array */[
  1,
  2,
  3
];

var reasonArrayFromList = $$Array.of_list(/* :: */[
      1,
      /* :: */[
        2,
        /* :: */[
          3,
          /* [] */0
        ]
      ]
    ]);

var reasonList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.reasonArray = reasonArray;
exports.reasonArrayFromList = reasonArrayFromList;
exports.reasonList = reasonList;
/* reasonArrayFromList Not a pure module */
