// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Stack$ReasonExamples = require("./data-structures/Stack.bs.js");

function string_to_list(str) {
  return $$Array.to_list(str.split(""));
}

function is_balanced(str) {
  var _stack = Stack$ReasonExamples.make(/* () */0);
  var _s = $$Array.to_list(str.split(""));
  while(true) {
    var s = _s;
    var stack = _stack;
    if (s) {
      switch (s[0]) {
        case "(" : 
            _s = s[1];
            _stack = Stack$ReasonExamples.push("(", stack);
            continue ;
        case ")" : 
            var match = Stack$ReasonExamples.pop(stack);
            if (match[0] === "(") {
              _s = s[1];
              _stack = match[1];
              continue ;
            } else {
              return false;
            }
        case "{" : 
            _s = s[1];
            _stack = Stack$ReasonExamples.push("{", stack);
            continue ;
        case "}" : 
            var match$1 = Stack$ReasonExamples.pop(stack);
            if (match$1[0] === "{") {
              _s = s[1];
              _stack = match$1[1];
              continue ;
            } else {
              return false;
            }
        default:
          _s = s[1];
          continue ;
      }
    } else {
      return Stack$ReasonExamples.is_empty(stack);
    }
  };
}

exports.string_to_list = string_to_list;
exports.is_balanced = is_balanced;
/* No side effect */
