// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var BinarySearchTree$ReasonExamples = require("../src/data-structures/BinarySearchTree.bs.js");

Jest.describe("make", (function (param) {
        return Jest.test("make", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* Node */[
                                  5,
                                  /* Leaf */0,
                                  /* Leaf */0
                                ], Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.make(5)));
                    }));
      }));

Jest.describe("make_empty", (function (param) {
        return Jest.test("make_empty", (function (param) {
                      return Jest.Expect[/* toBe */2](/* Leaf */0, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.make_empty(/* () */0)));
                    }));
      }));

Jest.describe("insert", (function (param) {
        return Jest.test("insert", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* Node */[
                                  5,
                                  /* Leaf */0,
                                  /* Leaf */0
                                ], Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.insert(5, BinarySearchTree$ReasonExamples.make_empty(/* () */0))));
                    }));
      }));

Jest.describe("mem", (function (param) {
        var tree = BinarySearchTree$ReasonExamples.tree_of_array(/* array */[
              5,
              6,
              2,
              1,
              3
            ]);
        Jest.test("returns true if value is a member", (function (param) {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(5, tree)));
              }));
        Jest.test("returns true if value is a member", (function (param) {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(6, tree)));
              }));
        Jest.test("returns true if value is a member", (function (param) {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(2, tree)));
              }));
        Jest.test("returns true if value is a member", (function (param) {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(1, tree)));
              }));
        Jest.test("returns true if value is a member", (function (param) {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(3, tree)));
              }));
        Jest.test("returns false if value is not a member", (function (param) {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(0, tree)));
              }));
        Jest.test("returns false if value is not a member", (function (param) {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(4, tree)));
              }));
        return Jest.test("returns false if value is not a member", (function (param) {
                      return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.mem(11, tree)));
                    }));
      }));

Jest.describe("sum", (function (param) {
        Jest.test("returns the sum of integers", (function (param) {
                return Jest.Expect[/* toBe */2](36, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.sum(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[
                                        7,
                                        15,
                                        3,
                                        1,
                                        10
                                      ]))));
              }));
        return Jest.test("returns the sum of integers", (function (param) {
                      return Jest.Expect[/* toBe */2](0, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.sum(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[]))));
                    }));
      }));

Jest.describe("height", (function (param) {
        Jest.test("returns 0 for an empty tree", (function (param) {
                return Jest.Expect[/* toBe */2](0, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.height(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[]))));
              }));
        return Jest.test("returns the height", (function (param) {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.height(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[
                                              7,
                                              15,
                                              16,
                                              1,
                                              10
                                            ]))));
                    }));
      }));

Jest.describe("size", (function (param) {
        Jest.test("returns 0 for an empty tree", (function (param) {
                return Jest.Expect[/* toBe */2](0, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.size(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[]))));
              }));
        Jest.test("returns the size", (function (param) {
                return Jest.Expect[/* toBe */2](5, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.size(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[
                                        5,
                                        6,
                                        2,
                                        1,
                                        3
                                      ]))));
              }));
        return Jest.test("returns the size", (function (param) {
                      return Jest.Expect[/* toBe */2](1, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.size(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[55]))));
                    }));
      }));

Jest.describe("min", (function (param) {
        Jest.test("returns 0 for an empty tree", (function (param) {
                return Jest.Expect[/* toBe */2](1, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.min(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[
                                        5,
                                        6,
                                        2,
                                        1,
                                        3
                                      ]))));
              }));
        return Jest.test("returns the size", (function (param) {
                      return Jest.Expect[/* toBe */2](55, Jest.Expect[/* expect */0](BinarySearchTree$ReasonExamples.min(BinarySearchTree$ReasonExamples.tree_of_array(/* array */[55]))));
                    }));
      }));

var a = "";

exports.a = a;
/*  Not a pure module */
