// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ListUtils$ReasonExamples = require("../src/ListUtils.bs.js");

Jest.describe("reverse", (function (param) {
        return Jest.test("reverse", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* :: */[
                                  5,
                                  /* :: */[
                                    4,
                                    /* :: */[
                                      3,
                                      /* :: */[
                                        2,
                                        /* :: */[
                                          1,
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ], Jest.Expect[/* expect */0](ListUtils$ReasonExamples.reverse(/* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              3,
                                              /* :: */[
                                                4,
                                                /* :: */[
                                                  5,
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

var a = "";

exports.a = a;
/*  Not a pure module */
