// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var ListUtils$ReasonExamples = require("../src/ListUtils.bs.js");

Jest.describe("reverse", (function (param) {
        return Jest.test("reverse", (function (param) {
                      return Jest.Expect.toEqual({
                                  hd: 5,
                                  tl: {
                                    hd: 4,
                                    tl: {
                                      hd: 3,
                                      tl: {
                                        hd: 2,
                                        tl: {
                                          hd: 1,
                                          tl: /* [] */0
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(ListUtils$ReasonExamples.reverse({
                                          hd: 1,
                                          tl: {
                                            hd: 2,
                                            tl: {
                                              hd: 3,
                                              tl: {
                                                hd: 4,
                                                tl: {
                                                  hd: 5,
                                                  tl: /* [] */0
                                                }
                                              }
                                            }
                                          }
                                        })));
                    }));
      }));

var a = "";

exports.a = a;
/*  Not a pure module */
