// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var StackFns$ReasonExamples = require("../src/StackFns.bs.js");

Jest.describe("is_balanced", (function (param) {
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(StackFns$ReasonExamples.is_balanced("{(ab()cde)}")));
              }));
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect.toEqual(false, Jest.Expect.expect(StackFns$ReasonExamples.is_balanced("{(}abcde)}")));
              }));
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect.toEqual(true, Jest.Expect.expect(StackFns$ReasonExamples.is_balanced("")));
              }));
        return Jest.test("is_balanced", (function (param) {
                      return Jest.Expect.toEqual(true, Jest.Expect.expect(StackFns$ReasonExamples.is_balanced("adf32")));
                    }));
      }));

var a = "";

exports.a = a;
/*  Not a pure module */
