// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var StackFns$ReasonExamples = require("../src/StackFns.bs.js");

Jest.describe("is_balanced", (function (param) {
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](StackFns$ReasonExamples.is_balanced("{(ab()cde)}")));
              }));
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](StackFns$ReasonExamples.is_balanced("{(}abcde)}")));
              }));
        Jest.test("is_balanced", (function (param) {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](StackFns$ReasonExamples.is_balanced("")));
              }));
        return Jest.test("is_balanced", (function (param) {
                      return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](StackFns$ReasonExamples.is_balanced("adf32")));
                    }));
      }));

var a = "";

exports.a = a;
/*  Not a pure module */
